describe('calculator app', () => {
  beforeEach(() => {
    cy.visit('../../../index.html')
  })

  it('all calculator buttons are correctly labelled', () => {
    // bottom row
    cy.get('#button0').should('have.text', '0')
    cy.get('#buttonDot').should('have.text', ' . ')
    cy.get('#buttonEquals').should('have.text', '=')
    cy.get('#buttonAddition').should('have.text', '+')

    // second from bottom row
    cy.get('#button1').should('have.text', '1')
    cy.get('#button2').should('have.text', '2')
    cy.get('#button3').should('have.text', '3')
    cy.get('#buttonSubtraction').should('have.text', '-')

    // third from bottom row
    cy.get('#button4').should('have.text', '4')
    cy.get('#button5').should('have.text', '5')
    cy.get('#button6').should('have.text', '6')
    cy.get('#buttonMultiplication').should('have.text', 'x')

    // top row
    cy.get('#button7').should('have.text', '7')
    cy.get('#button8').should('have.text', '8')
    cy.get('#button9').should('have.text', '9')
    cy.get('#buttonDivision').should('have.text', '÷')
    cy.get('#buttonClear').should('have.text', 'C')
  })

  it('has a display with a 0 on load', () => {
    cy.get('#display').exists
    cy.get('#display').should('have.text', '0')
  })

  it('each number shows on screen when the corresponding button is clicked and the C button clears the display', () => {
    cy.get('#button1').click()
    cy.get('#display').should('have.text', '1')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button2').click()
    cy.get('#display').should('have.text', '2')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button3').click()
    cy.get('#display').should('have.text', '3')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button5').click()
    cy.get('#display').should('have.text', '5')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button6').click()
    cy.get('#display').should('have.text', '6')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button7').click()
    cy.get('#display').should('have.text', '7')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button8').click()
    cy.get('#display').should('have.text', '8')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button9').click()
    cy.get('#display').should('have.text', '9')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button0').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
  })

  it('Basic Calculations - Single Integer - Addition (1 + 2 = 3)', () => {
    cy.get('#button1').click()
    cy.get('#buttonAddition').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '3')})

  it('Basic Calculations - Single Integer - Subtraction (3 - 1 = 2)', () => {
    cy.get('#button3').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#button1').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '2')})

  it('Basic Calculations - Single Integer - Division (6 / 3 = 2)', () => {
    cy.get('#button6').click()
    cy.get('#buttonDivision').click()
    cy.get('#button3').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '2')})


  it('Basic Calculations - Single Integer - Multiplication (4 * 2 = 8)', () => {
    cy.get('#button4').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '8')})

  it('Basic Calculations - Larger Integers - Addition (12 + 23 = 35)', () => {
    cy.get('#button1').click()
    cy.get('#button2').click()
    cy.get('#buttonAddition').click()
    cy.get('#button2').click()
    cy.get('#button3').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '35')})


  it('Basic Calculations - Larger Integers - Subtraction (36 - 15 = 21)', () => {
    cy.get('#button3').click()
    cy.get('#button6').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#button1').click()
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '21')})

  it('Basic Calculations - Larger Integers - Division (999 / 9 = 111)', () => {
    cy.get('#button9').click()
    cy.get('#button9').click()
    cy.get('#button9').click()
    cy.get('#buttonDivision').click()
    cy.get('#button9').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '111')})

  it('Basic Calculations - Larger Integers - Multiplication (10 x 99 = 990)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button9').click()
    cy.get('#button9').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '990')})

  it('Basic Calculations - Decimals - Addition (1.2 + 2.3 = 3.5)', () => {
    cy.get('#button1').click()
    cy.get('#buttonDot').click()
    cy.get('#button2').click()
    cy.get('#buttonAddition').click()
    cy.get('#button2').click()
    cy.get('#buttonDot').click()
    cy.get('#button3').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '3.5')})

  it('Basic Calculations - Decimals - Subtraction (3.6 - 1.5 = 2.1)', () => {
    cy.get('#button3').click()
    cy.get('#buttonDot').click()
    cy.get('#button6').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#button1').click()
    cy.get('#buttonDot').click()
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '2.1')})

  it('Basic Calculations - Decimals - Division (99.9 / 2 = 49.95)', () => {
    cy.get('#button9').click()
    cy.get('#button9').click()
    cy.get('#buttonDot').click()
    cy.get('#button9').click()
    cy.get('#buttonDivision').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '49.95')})

  it('Basic Calculations - Decimals - Multiplication (10.2 x 99.2 = 1011.84)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#buttonDot').click()
    cy.get('#button2').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button9').click()
    cy.get('#button9').click()
    cy.get('#buttonDot').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '1011.84')})

  it('Chaining Equations - Addition (1 + 2 + 3 = 6 + 4 + 5 = 15)', () => {
    cy.get('#button1').click()
    cy.get('#buttonAddition').click()
    cy.get('#button2').click()
    cy.get('#buttonAddition').click()
    cy.get('#display').should('have.text', '3')
    cy.get('#button3').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '6')
    cy.get('#buttonAddition').click()
    cy.get('#button4').click()
    cy.get('#buttonAddition').click()
    cy.get('#display').should('have.text', '10')
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '15')})


  it('Chaining Equations - Subtraction (100 - 1 - 9 = 90 - 20 - 5 = 65)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#button0').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#button1').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#display').should('have.text', '99')
    cy.get('#button9').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '90')
    cy.get('#buttonSubtraction').click()
    cy.get('#button2').click()
    cy.get('#button0').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#display').should('have.text', '70')
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '65')})

  it('Chaining Equations - Multiplication (2 x 5 x 3 = 30 x 3 x 2 = 180)', () => {
    cy.get('#button2').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button5').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#display').should('have.text', '10')
    cy.get('#button3').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '30')
    cy.get('#buttonMultiplication').click()
    cy.get('#button3').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '180')})

  it('Chaining Equations - Division (100 / 2 / 5 = 10 / 1 = 10 / 2 = 5)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#button0').click()
    cy.get('#buttonDivision').click()
    cy.get('#button2').click()
    cy.get('#buttonDivision').click()
    cy.get('#display').should('have.text', '50')
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '10')
    cy.get('#buttonDivision').click()
    cy.get('#button1').click()
    cy.get('#buttonEquals').click()
    cy.get('#buttonDivision').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '5')})

  it('Chaining Equations - Mixed Equation (100 / 2 * 5 = 250 - 200 = 50 + 5 = 55) ', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#button0').click()
    cy.get('#buttonDivision').click()
    cy.get('#button2').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#display').should('have.text', '50')
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '250')
    cy.get('#buttonSubtraction').click()
    cy.get('#button2').click()
    cy.get('#button0').click()
    cy.get('#button0').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '50')
    cy.get('#buttonAddition').click()
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '55')})

  it('Clear Button Functionality - Clears Addition Chain Midway (10 + 5 + 2; C; 2 + 2 = 4)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#buttonAddition').click()
    cy.get('#button5').click()
    cy.get('#buttonAddition').click()
    cy.get('#display').should('have.text', '15')
    cy.get('#button2').click()
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button2').click()
    cy.get('#buttonAddition').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '4')})

  it('Clear Button Functionality - Clears Subtraction Chain Midway (10 - 2 - 1; C; 4 - 1 = 3)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#button2').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#display').should('have.text', '8')
    cy.get('#button1').click()
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button4').click()
    cy.get('#buttonSubtraction').click()
    cy.get('#button1').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '3')})

  it('Clear Button Functionality - Clears Multiplication Chain Midway (5 x 2 x 3; C; 3 x 4 = 12)', () => {
    cy.get('#button5').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button2').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#display').should('have.text', '10')
    cy.get('#button3').click()
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button3').click()
    cy.get('#buttonMultiplication').click()
    cy.get('#button4').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '12')})

  it('Clear Button Functionality - Clears Division Chain Midway (100 / 2 / 2; C; 20 / 5 = 4)', () => {
    cy.get('#button1').click()
    cy.get('#button0').click()
    cy.get('#button0').click()
    cy.get('#buttonDivision').click()
    cy.get('#button2').click()
    cy.get('#buttonDivision').click()
    cy.get('#display').should('have.text', '50')
    cy.get('#button2').click()
    cy.get('#buttonClear').click()
    cy.get('#display').should('have.text', '0')
    cy.get('#button2').click()
    cy.get('#button0').click()
    cy.get('#buttonDivision').click()
    cy.get('#button5').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '4')})

  it('Decimal Button Functionality - Adding multiple decimals to a number is not allowed', () =>{
    cy.get('#button1').click()
    cy.get('#buttonDot').click()
    cy.get('#button1').click()
    cy.get('#buttonDot').click()
    cy.get('#display').should('have.text', '1.1')
    cy.get('#button2').click()
    cy.get('#display').should('have.text', '1.12')})

  it('Decimal Button Functionality - Pressing the decimal button before numbers allows a "0.x" decimal number to be entered', () =>{
    cy.get('#buttonDot').click()
    cy.get('#button1').click()
    cy.get('#display').should('have.text', '0.1')
    cy.get('#buttonAddition').click()
    cy.get('#buttonDot').click()
    cy.get('#button2').click()
    cy.get('#display').should('have.text', '0.2')
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '0.3')})

  it('Equals Button Functionality - Pressing the equals button multiple times after a calculation does nothing ', () =>{
    cy.get('#button1').click()
    cy.get('#buttonAddition').click()
    cy.get('#button2').click()
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '3')
    cy.get('#buttonEquals').click()
    cy.get('#display').should('have.text', '3')
  })

  it('0 Button Functionality - 0 Button does not add a zero to the front of numbers', () =>{
    cy.get('#button0').click()
    cy.get('#button1').click()
    cy.get('#display').should('have.text', '1')
  })

  it('Dividing by 0 displays an error message', () =>{
    cy.get('#button0').click()
    cy.get('#buttonDivision').click()
    cy.get('#button0').click()
    cy.get('#buttonEquals').click()
    const alertShown = cy.stub().as('alertShown')
    cy.on('window:alert', alertShown)
    cy.get("@alertShown").should('have.been.calledOnceWith', 'Dividing by zero will end us all!')
    cy.get('#display').should('have.text', 'NaN')
  })
})